/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

/**
 *
 * @author juald
 */
public class VistaPizzas extends javax.swing.JDialog {

    /**
     * Creates new form VistaPizzas2
     */
    public VistaPizzas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HacerPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        TipoPizza = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ExtraQueso = new javax.swing.JCheckBox();
        Bacon = new javax.swing.JCheckBox();
        AceitunasNegras = new javax.swing.JCheckBox();
        PolloBraseado = new javax.swing.JCheckBox();
        Anchoas = new javax.swing.JCheckBox();
        JamonYork = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        HacerPedido.setText("Hacer pedido");
        HacerPedido.setActionCommand("HacerPedido");

        jLabel1.setText("¿Qué tipo de pizza desea?");

        Salir.setText("Salir");
        Salir.setActionCommand("Salir2");

        TipoPizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peperoni", "Cuatro quesos", "Barbacoa", "Marinera" }));
        TipoPizza.setSelectedIndex(-1);
        TipoPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoPizzaActionPerformed(evt);
            }
        });

        jLabel2.setText("¿Desea ingredientes extra? (Máximo 3)");

        ExtraQueso.setText("Extra de queso");

        Bacon.setText("Bacon");

        AceitunasNegras.setText("Aceitunas negras");

        PolloBraseado.setText("Pollo braseado");

        Anchoas.setText("Anchoas");

        JamonYork.setText("Jamón York");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Pedido nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TipoPizza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(HacerPedido)
                            .addGap(18, 18, 18)
                            .addComponent(Salir))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ExtraQueso)
                                .addComponent(PolloBraseado))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Anchoas)
                                .addComponent(Bacon))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AceitunasNegras)
                                .addComponent(JamonYork)))))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TipoPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExtraQueso)
                    .addComponent(Bacon)
                    .addComponent(AceitunasNegras))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PolloBraseado)
                    .addComponent(Anchoas)
                    .addComponent(JamonYork))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HacerPedido)
                    .addComponent(Salir))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoPizzaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox AceitunasNegras;
    public javax.swing.JCheckBox Anchoas;
    public javax.swing.JCheckBox Bacon;
    public javax.swing.JCheckBox ExtraQueso;
    public javax.swing.JButton HacerPedido;
    public javax.swing.JCheckBox JamonYork;
    public javax.swing.JCheckBox PolloBraseado;
    public javax.swing.JButton Salir;
    public javax.swing.JComboBox<String> TipoPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
